"""Regenerate the dev workspace fixture used by the Files browser (BUILD-SPEC §5.6, Phase 1).

    uv run python scripts/make_dev_workspace.py

Writes ``<repo>/exampledata/workspace`` (gitignored via the blanket ``exampledata/`` rule).
Idempotent: wipes and recreates the tree every run. Point ``ASTRA_WORKSPACE_DIR`` at it in
``backend/.env`` for local dev.

The tree exercises every guard in ``astra/files.py``:

* ordinary nested directories/files (text, markdown, source, image, html)
* a file with a unicode name containing a space (NFC-normalized, like real uploads)
* a binary file over 10 MB (exercises the download streaming path and the "not previewable as
  text" branch of ``/api/files/content``)
* a symlink whose target is *outside* the workspace tree entirely
* a symlinked directory (also outside the tree) — descending into it must be refused
* a would-be deny-wall hit (a ``logs/`` subdirectory and a ``config.yaml`` file) so the deny-wall
  can be exercised even though this is a plain workspace, not a Hermes home

Also writes two sibling directories outside the workspace root (``workspace-outside-*``) that the
symlinks point at, so "outside the tree" is unambiguous.
"""

from __future__ import annotations

import os
import shutil
import struct
import zlib
from pathlib import Path

REPO_DIR = Path(__file__).resolve().parents[2]
EXAMPLEDATA_DIR = REPO_DIR / "exampledata"
WORKSPACE_DIR = EXAMPLEDATA_DIR / "workspace"
OUTSIDE_FILE_DIR = EXAMPLEDATA_DIR / "workspace-outside-secret"
OUTSIDE_DIR_DIR = EXAMPLEDATA_DIR / "workspace-outside-secret-dir"

BIG_BINARY_SIZE = 11 * 1024 * 1024  # > 10 MB


def _png_chunk(tag: bytes, data: bytes) -> bytes:
    return struct.pack(">I", len(data)) + tag + data + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)


def make_png_bytes(width: int = 64, height: int = 64) -> bytes:
    """A tiny valid RGB PNG (a solid-ish checkerboard), built with stdlib only (no Pillow dep)."""
    rows = []
    for y in range(height):
        row = bytearray([0])  # filter type 0 (none)
        for x in range(width):
            on = (x + y) % 2 == 0
            row += bytes((60, 130, 246) if on else (240, 240, 240))
        rows.append(bytes(row))
    raw = b"".join(rows)
    ihdr = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    return (
        b"\x89PNG\r\n\x1a\n"
        + _png_chunk(b"IHDR", ihdr)
        + _png_chunk(b"IDAT", zlib.compress(raw, 9))
        + _png_chunk(b"IEND", b"")
    )


ICON_SVG = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
  <circle cx="12" cy="12" r="10" fill="#3c82f6" />
  <text x="12" y="16" font-size="10" text-anchor="middle" fill="white">A</text>
</svg>
"""

INDEX_HTML = """<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><title>Dev workspace artifact</title></head>
<body>
  <h1>Hello from the dev workspace</h1>
  <p>This file exercises the "force download for text/html" guard in the Files download endpoint.</p>
</body>
</html>
"""

README_MD = """# Dev workspace

This tree is generated by `backend/scripts/make_dev_workspace.py` for exercising the Files
browser locally. See that script for what each fixture is for.

- `notes/` — plain text and markdown
- `src/` — source files of a few languages, for syntax highlighting
- `assets/` — a PNG and an SVG, for inline image preview
- `docs/index.html` — must always force-download (never render inline)
- `data/big_binary.bin` — > 10 MB, exercises streamed download and the binary-preview refusal
- `unicode  files/` — a directory + filename with unicode and a space
- `link-outside-file` / `link-outside-dir` — symlinks that must be refused outright
- `config.yaml`, `logs/` — deny-wall probes (not real Hermes state, just guard bait)
"""

TODO_TXT = "- [ ] write the files browser\n- [x] write the logs tailer\n- [ ] ship it\n"

IDEAS_MD = """# Ideas

1. Virtualize the directory listing.
2. Syntax highlight previews with @mantine/code-highlight.
3. Drag-and-drop upload with progress.
"""

MAIN_PY = '''"""Toy module used only as a Files-preview fixture."""


def fib(n: int) -> int:
    a, b = 0, 1
    for _ in range(n):
        a, b = b, a + b
    return a


if __name__ == "__main__":
    print([fib(i) for i in range(10)])
'''

UTILS_JS = """export function clamp(value, min, max) {
  return Math.min(max, Math.max(min, value));
}
"""

STYLES_CSS = """:root {
  --accent: #3c82f6;
}
body {
  font-family: system-ui, sans-serif;
}
"""

HELPERS_TS = """export interface Point {
  x: number;
  y: number;
}

export function distance(a: Point, b: Point): number {
  return Math.hypot(a.x - b.x, a.y - b.y);
}
"""

FAKE_CONFIG_YAML = "# deny-wall probe: this must never be listed/read even though it's a plain workspace file\nkey: not-a-real-secret\n"


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> None:
    for d in (WORKSPACE_DIR, OUTSIDE_FILE_DIR, OUTSIDE_DIR_DIR):
        if d.exists() or d.is_symlink():
            shutil.rmtree(d, ignore_errors=True)
            if d.is_symlink() or d.exists():
                d.unlink(missing_ok=True)

    WORKSPACE_DIR.mkdir(parents=True)

    _write_text(WORKSPACE_DIR / "README.md", README_MD)
    _write_text(WORKSPACE_DIR / "notes" / "todo.txt", TODO_TXT)
    _write_text(WORKSPACE_DIR / "notes" / "ideas.md", IDEAS_MD)
    _write_text(WORKSPACE_DIR / "src" / "app" / "main.py", MAIN_PY)
    _write_text(WORKSPACE_DIR / "src" / "app" / "utils.js", UTILS_JS)
    _write_text(WORKSPACE_DIR / "src" / "app" / "styles.css", STYLES_CSS)
    _write_text(WORKSPACE_DIR / "src" / "lib" / "helpers.ts", HELPERS_TS)
    _write_text(WORKSPACE_DIR / "docs" / "index.html", INDEX_HTML)
    _write_text(WORKSPACE_DIR / "assets" / "icon.svg", ICON_SVG)

    (WORKSPACE_DIR / "assets").mkdir(parents=True, exist_ok=True)
    (WORKSPACE_DIR / "assets" / "logo.png").write_bytes(make_png_bytes())

    # Unicode + space filename and directory (NFC, like a real browser upload).
    unicode_dir = WORKSPACE_DIR / "unicode \U0001f600 files"
    unicode_dir.mkdir(parents=True, exist_ok=True)
    _write_text(unicode_dir / "café ünicode notes.txt", "résumé: unicode + space filenames must round-trip.\n")

    # > 10 MB binary — streamed chunks, never held whole in memory here either.
    data_dir = WORKSPACE_DIR / "data"
    data_dir.mkdir(parents=True, exist_ok=True)
    with (data_dir / "big_binary.bin").open("wb") as fh:
        remaining = BIG_BINARY_SIZE
        chunk = os.urandom(1024 * 1024)
        while remaining > 0:
            n = min(len(chunk), remaining)
            fh.write(chunk[:n])
            remaining -= n

    # Deny-wall probes: a plain workspace should still never expose these names/dirs.
    _write_text(WORKSPACE_DIR / "config.yaml", FAKE_CONFIG_YAML)
    _write_text(WORKSPACE_DIR / "logs" / "would-be-hermes.log", "this directory name is on the deny-wall\n")

    # Outside-the-tree targets + the symlinks pointing at them.
    OUTSIDE_FILE_DIR.mkdir(parents=True, exist_ok=True)
    (OUTSIDE_FILE_DIR / "secret.txt").write_text("if you can read this via Files, the symlink guard is broken\n")
    OUTSIDE_DIR_DIR.mkdir(parents=True, exist_ok=True)
    (OUTSIDE_DIR_DIR / "also-secret.txt").write_text("this lives in a symlinked-to directory outside the workspace\n")

    (WORKSPACE_DIR / "link-outside-file").symlink_to(OUTSIDE_FILE_DIR / "secret.txt")
    (WORKSPACE_DIR / "link-outside-dir").symlink_to(OUTSIDE_DIR_DIR, target_is_directory=True)

    print(f"wrote dev workspace at {WORKSPACE_DIR}")


if __name__ == "__main__":
    main()
